export const UPDATE_MEDICAL_START = 'UPDATE_MEDICAL_START';
export const UPDATE_MEDICAL_SUCCESS = 'UPDATE_MEDICAL_SUCCESS';
export const UPDATE_MEDICAL_FAIL = 'UPDATE_MEDICAL_FAIL';



export const GET_MEDICAL_START = 'GET_MEDICAL_START';
export const GET_MEDICAL_SUCCESS = 'GET_MEDICAL_SUCCESS';
export const GET_MEDICAL_FAIL = 'GET_MEDICAL_FAIL';

